// Code generated by "stringer -type=ColorLevel"; DO NOT EDIT.

package gchalk

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LevelNone-0]
	_ = x[LevelBasic-1]
	_ = x[LevelAnsi256-2]
	_ = x[LevelAnsi16m-3]
}

const _ColorLevel_name = "LevelNoneLevelBasicLevelAnsi256LevelAnsi16m"

var _ColorLevel_index = [...]uint8{0, 9, 19, 31, 43}

func (i ColorLevel) String() string {
	if i < 0 || i >= ColorLevel(len(_ColorLevel_index)-1) {
		return "ColorLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorLevel_name[_ColorLevel_index[i]:_ColorLevel_index[i+1]]
}
